version: "3.7"
services:
 nginx:
   image: nginx:1.22.0
   networks:
     - network
   volumes:
     - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
     - static-volume:/data/static
     - media-volume:/data/media
   ports:
     - 80:80
   depends_on:
     - prpc_container_gunicorn

 prpc_container_gunicorn:
   image: prpc_image:8
   networks:
     - network
   volumes:
     - static-volume:/home/prpc/staticfiles
     - media-volume:/home/prpc/media
     - /home/django_course/.env:/home/prpc/.env
   secrets:
     - MYSQL_PASSWORD
     - DJANGO_SECRET_KEY
   depends_on:
     - mariadb

 mariadb:
   image: mariadb:10.5
   networks:
     - network
   volumes:
     - maria-database:/var/lib/mysql
   secrets:
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
   environment:
     MYSQL_DATABASE: django
     MYSQL_USER: prpc8575
     MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
     MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD

networks:
 network:

volumes:
 static-volume:
 media-volume:
 maria-database:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true