version: "3.7"
services:
  nginx:
    image: nginx:1.22.0
    networks:
      - network
    volumes:
      - /home/django_course/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
      - /home/django_course/certbot/conf:/etc/letsencrypt
      - /home/django_course/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - prpc_container_gunicorn

  certbot:
    image: certbot/certbot
    volumes:
      - /home/django_course/certbot/conf:/etc/letsencrypt
      - /home/django_course/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email kshhyh00@gmail.com -d prpc.co.kr -d www.prpc.co.kr --agree-tos --force-renewal

  prpc_container_gunicorn: #network로 묶이기 때문에 name-space 정보로 넣어줘야한다. django로 넣으면 안된다.
    image: prpc_image:4
    networks:
      - network
    volumes:
      - static-volume:/home/prpc/staticfiles
      - media-volume:/home/prpc/media
      - /home/django_course/.env:/home/prpc/.env
    secrets:
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      MYSQL_DATABASE: django
      MYSQL_USER: prpc8575
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD



#상기 선언한 network와 volume들을 변수처럼? 명기
networks:
  network:

volumes:
  static-volume:
  media-volume:
  maria-database:

secrets:
   DJANGO_SECRET_KEY:
     external: true
   MYSQL_PASSWORD:
     external: true
   MYSQL_ROOT_PASSWORD:
     external: true
