# Generated by Django 4.1.5 on 2025-08-31 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookingapp", "0013_alter_booking_booking_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "예약 생성"),
                            ("UPDATE", "예약 변경"),
                            ("DELETE", "예약 취소"),
                            ("APPROVE", "예약 승인"),
                            ("REJECT", "예약 거절"),
                            ("BLOCK", "예약 차단"),
                            ("UNBLOCK", "예약 차단 해제"),
                        ],
                        max_length=10,
                        verbose_name="액션 타입",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="로그 생성 시간"
                    ),
                ),
                ("booking_date", models.DateField(verbose_name="예약 날짜")),
                (
                    "booking_time",
                    models.CharField(max_length=16, verbose_name="예약 시간"),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="이전 상태"
                    ),
                ),
                ("new_status", models.CharField(max_length=10, verbose_name="새 상태")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookingapp.booking",
                        verbose_name="예약",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_logs_as_modifier",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="변경자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_logs_as_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="예약자",
                    ),
                ),
            ],
            options={
                "verbose_name": "예약 로그",
                "verbose_name_plural": "예약 로그 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
