# Generated by Django 4.1.5 on 2025-09-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinglog",
            name="booking_rn",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="직접예약자명"
            ),
        ),
    ]
