# Generated by Django 4.1.5 on 2023-03-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
