# Generated by Django 4.1.5 on 2023-02-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_profile_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chart_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
