# Generated by Django 4.1.5 on 2023-07-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_profile_chart_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chart_num',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
